# Generated by Django 2.2.7 on 2020-04-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
